# Site
title: sara lana

# URL
url: http://saralana.xyz
baseurl: ''

# default url for pages/posts
permalink: :title/

# site directory structure specifications | arquivos temporários de css no mesmo diretório
include: ['_pages']
sass:
  sass_dir: css

# Build settings
markdown: kramdown
port: 4323

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
twitter_user: "sara_lana_"
  
social:
  github: "https://github.com/saralana"
  twitter: "https://twitter.com/sara_lana_"
  vimeo: "https://vimeo.com/saralana"
  instagram: "https://www.instagram.com/inumerosprimos"
  soundcloud: "https://soundcloud.com/sara_lana"
  envelope-o: "mailto:saralgc@gmail.com"
