# Site
title: sara lana

# URL
url: http://inumerosprimos.xyz
baseurl: ''

# default url for pages/posts
permalink: :title/

# site directory structure specifications | arquivos temporários de css no mesmo diretório
include: ['_pages']
sass:
  sass_dir: css

# Build settings
markdown: kramdown
port: 4323

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook_user: "facebookUserName" 
  twitter_user: "cambiosara"
  facebook: "https://www.facebook.com/user"
  instagram: "https://www.instagram.com/inumerosprimos"
  github: "https://github.com/saralana"
  twitter: "https://twitter.com/cambiosara"
  youtube: ""
  vimeo: "https://vimeo.com/saralana"
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:saralgc@gmail.com"
  twitter_user: "user"
